### ISSUE TITLE
Missing project documentation.

### ISSUE THREAD

**Issue by wtrocki** [kiegroup/appformer#99]
I would like to contribute the project. Is it possible to get some guidance in order to try this out/run it or contribute?

Questions:

1) How to run/contribute to project?
2) Where to find issues/bugs?
3) What is the project license?

It will be good to get some quick hints in README.md file.

ping @pefernan @wmedvede

**Comment by ederign** [comment]
Hi @wtrocki. We are moving some projects (uberfire/dashbuilder/stunner/) inside this repo in order to make a more clear vision of AppFormer project. Stay tuned.
